In [381]:
import pandas as pd
import os
# dp03 is econ data, dp02 is social, dp05 is race

In [386]:
def combine_f(x,y,z,year):
    combined = z.merge(x.merge(y,how = 'inner',on = 'GEO.id'),how = 'inner', on = 'GEO.id')
    combined.columns = combined.iloc[0]
    combined = combined.drop(0)
    return combined

In [387]:
directory = os.curdir
li = []
year_list = [10,11,12,13,14,15,16]
for d in os.listdir(directory):
    if d.startswith("2"):
        for files in os.listdir(d) :
            if files.endswith('.csv'):
                year = d[:4]
                path = os.path.join(directory, d)
                file_path = os.path.join(path, files)
                if('DP03' in files):
                    econ = pd.read_csv(file_path)
                elif('DP02' in files):
                    social = pd.read_csv(file_path)
                elif('DP05' in files):
                    race = pd.read_csv(file_path)
        combine = combine_f(econ,social,race,year)
        combine.to_csv(year + ' combined.csv')
    else:
        continue

In [388]:
x = pd.read_csv('2013/ACS_13_5YR_DP02_with_ann.csv')
y = pd.read_csv('2013/ACS_13_5YR_DP03_with_ann.csv')
z = pd.read_csv('2013/ACS_13_5YR_DP05_with_ann.csv')

In [391]:
pd.read_csv('2010 combined.csv').head()

,Unnamed: 0,Id,Id2,Geography,Estimate; SEX AND AGE - Total population,Estimate Margin of Error; SEX AND AGE - Total population,Percent; SEX AND AGE - Total population,Percent Margin of Error; SEX AND AGE - Total population,Estimate; SEX AND AGE - Male,Estimate Margin of Error; SEX AND AGE - Male,...,Percent; ANCESTRY - Ukrainian,Percent Margin of Error; ANCESTRY - Ukrainian,Estimate; ANCESTRY - Welsh,Estimate Margin of Error; ANCESTRY - Welsh,Percent; ANCESTRY - Welsh,Percent Margin of Error; ANCESTRY - Welsh,Estimate; ANCESTRY - West Indian (excluding Hispanic origin groups),Estimate Margin of Error; ANCESTRY - West Indian (excluding Hispanic origin groups),Percent; ANCESTRY - West Indian (excluding Hispanic origin groups),Percent Margin of Error; ANCESTRY - West Indian (excluding Hispanic origin groups)
0,1,1400000US17031010100,17031010100,"Census Tract 101, Cook County, Illinois",5303,782,5303,(X),2157,369,...,0.0,0.6,0,119,0.0,0.6,182,141,3.4,2.9
1,2,1400000US17031010201,17031010201,"Census Tract 102.01, Cook County, Illinois",5924,952,5924,(X),2849,476,...,1.3,1.7,0,119,0.0,0.5,343,272,5.8,4.7
2,3,1400000US17031010202,17031010202,"Census Tract 102.02, Cook County, Illinois",2981,499,2981,(X),1486,269,...,0.0,1.1,0,119,0.0,1.1,253,205,8.5,6.9
3,4,1400000US17031010300,17031010300,"Census Tract 103, Cook County, Illinois",6475,810,6475,(X),3387,428,...,1.0,1.1,11,18,0.2,0.3,130,106,2.0,1.7
4,5,1400000US17031010400,17031010400,"Census Tract 104, Cook County, Illinois",4651,611,4651,(X),2180,369,...,0.0,0.7,101,121,2.2,2.6,0,119,0.0,0.7

In [392]:
delete_list = [104,
301.01,
301.03,
314,
812.02,
814.02,
3907,
4101,
4109,
4110,
4307,
4314,
8004,
8012,
8087.02,
8094,
8365,
9900]
delete_list = [str(i) for i in delete_list]
# x = pd.read_csv('combined/2010 combined.csv')

In [393]:
overlay = pd.read_csv('overlay')

In [394]:
tract_overlay = overlay['NAMELSAD10'].apply(lambda x: x.split()[2])

In [396]:
tract_overlay = tract_overlay.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [397]:
tract_overlay # might be a problem to dealt with later

array(['8202.02', '8202.01', '8062.01', ..., '8047.15', '8093', '8095'],
      dtype=object)

In [400]:
# clean all combine files
def clean(x):
    x['Geography'] = x['Geography'].apply(lambda x: x.split()[2][:-1])
    x = x.set_index('Geography').drop(delete_list)
    return x.groupby(x.index).first()

In [401]:
path = os.path.join(directory, 'combined')
for d in os.listdir(path):
    if d.endswith("d.csv"):
        df = pd.read_csv(os.path.join(path, d))
        cleaned = clean(df)
        cleaned.to_csv(d)

/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,334,335,338,339,348,349,352,353,356,357,360,361,364,365,368,369,376,377,384,385,388,389,392,393,400,401,408,409,416,417,420,421,424,425,428,429,432,433,436,437,438,439,448,449,452,453,456,457,460,461,464,465,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,512,513,516,517,520,521,528,529,532,533,536,537,540,541,548,549,552,553,556,557,560,561,564,565,568,569,572,573,576,577,580,581,584,585,586,587,590,591,596,597,598,599,604,605,606,607,612,613,620,621,628,629,636,637,644,645,648,649,652,653,656,657,660,661,664,665,668,669,672,673,676,677,680,681,686,687,690,691,702,703,724,725,728,729,732,733,736,737,744,745,760,761,764,765,768,769,772,773,780,781,784,785,788,789,792,793,800,801,804,805,808,809,812,813,816,817,820,821,828,829,852,853,856,857,860,861,864,865,868,869,872,873,876,877,880,881,884,885,888,889,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,938,939,942,943,946,947,948,949,952,953,962,963,966,967,970,971,974,975,978,979,982,983,990,991,994,995,998,999,1002,1003,1006,1007,1014,1015,1018,1019,1022,1023,1026,1027,1030,1031,1040,1041,1044,1045,1048,1049,1052,1053,1056,1057,1102,1103,1106,1107,1110,1111,1114,1115,1118,1119,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1150,1151,1154,1155,1158,1159,1166,1167,1174,1175,1182,1183,1190,1191,1198,1199,1206,1207,1210,1211,1214,1215,1218,1219,1222,1223,1226,1227,1230,1231,1238,1239,1242,1243,1246,1247,1250,1251,1254,1255,1258,1259,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1366,1367,1370,1371,1374,1375,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475,1478,1479,1482,1483,1486,1487) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,16,17,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,70,71,72,73,78,79,82,83,86,87,90,91,94,95,98,99,106,107,110,111,112,113,122,123,126,127,128,129,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,234,235,238,239,242,243,246,247,250,251,258,259,262,263,266,267,270,271,274,275,278,279,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,326,327,330,331,334,335,338,339,342,343,354,355,358,359,368,369,372,373,376,377,380,381,384,385,388,389,396,397,404,405,408,409,412,413,420,421,428,429,436,437,440,441,444,445,448,449,452,453,456,457,458,459,468,469,472,473,476,477,480,481,484,485,492,493,496,497,500,501,504,505,508,509,512,513,516,517,520,521,524,525,528,529,532,533,536,537,540,541,548,549,552,553,556,557,560,561,568,569,572,573,576,577,580,581,584,585,588,589,592,593,596,597,600,601,604,605,610,611,616,617,618,619,624,625,626,627,632,633,640,641,648,649,656,657,664,665,668,669,672,673,676,677,680,681,684,685,688,689,692,693,696,697,700,701,706,707,710,711,722,723,726,727,744,745,748,749,752,753,756,757,764,765,780,781,784,785,788,789,792,793,820,821,824,825,828,829,832,833,836,837,840,841,848,849,872,873,876,877,880,881,884,885,888,889,892,893,896,897,900,901,904,905,908,909,918,919,922,923,926,927,930,931,934,935,938,939,942,943,946,947,950,951,954,955,958,959,962,963,966,967,968,969,972,973,982,983,986,987,990,991,994,995,998,999,1002,1003,1010,1011,1014,1015,1018,1019,1022,1023,1026,1027,1034,1035,1038,1039,1042,1043,1046,1047,1050,1051,1060,1061,1064,1065,1072,1073,1076,1077,1122,1123,1126,1127,1130,1131,1134,1135,1138,1139,1146,1147,1150,1151,1154,1155,1158,1159,1162,1163,1166,1167,1170,1171,1174,1175,1178,1179,1186,1187,1194,1195,1202,1203,1210,1211,1218,1219,1226,1227,1230,1231,1234,1235,1238,1239,1242,1243,1246,1247,1250,1251,1258,1259,1262,1263,1266,1267,1270,1271,1274,1275,1278,1279,1354,1355,1358,1359,1362,1363,1366,1367,1370,1371,1374,1375,1378,1379,1382,1383,1386,1387,1390,1391,1394,1395,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475,1478,1479,1482,1483,1486,1487,1490,1491,1494,1495,1498,1499,1502,1503,1506,1507,1514,1515,1518,1519) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,336,337,340,341,344,345,348,349,352,353,356,357,364,365,372,373,376,377,380,381,388,389,396,397,404,405,408,409,412,413,416,417,420,421,424,425,426,427,436,437,440,441,444,445,448,449,452,453,460,461,464,465,468,469,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,516,517,520,521,524,525,528,529,536,537,540,541,544,545,548,549,552,553,556,557,560,561,564,565,568,569,572,573,574,575,578,579,584,585,586,587,592,593,594,595,600,601,608,609,616,617,624,625,632,633,636,637,640,641,644,645,648,649,652,653,656,657,660,661,664,665,668,669,674,675,678,679,690,691,694,695,702,703,712,713,716,717,720,721,724,725,732,733,748,749,752,753,756,757,760,761,768,769,772,773,776,777,780,781,788,789,792,793,796,797,800,801,804,805,808,809,816,817,840,841,844,845,848,849,852,853,856,857,860,861,864,865,868,869,872,873,876,877,886,887,890,891,894,895,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,936,937,940,941,950,951,954,955,958,959,962,963,966,967,970,971,978,979,982,983,986,987,990,991,994,995,1002,1003,1006,1007,1010,1011,1014,1015,1018,1019,1028,1029,1032,1033,1040,1041,1044,1045,1090,1091,1094,1095,1098,1099,1102,1103,1106,1107,1114,1115,1118,1119,1122,1123,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1154,1155,1162,1163,1170,1171,1178,1179,1186,1187,1194,1195,1198,1199,1202,1203,1206,1207,1210,1211,1214,1215,1218,1219,1226,1227,1230,1231,1234,1235,1238,1239,1242,1243,1246,1247,1322,1323,1326,1327,1330,1331,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1370,1371,1374,1375,1378,1379,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,336,337,340,341,344,345,348,349,352,353,356,357,364,365,372,373,376,377,380,381,388,389,396,397,404,405,408,409,412,413,416,417,420,421,424,425,426,427,436,437,440,441,444,445,448,449,452,453,460,461,464,465,468,469,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,516,517,520,521,524,525,528,529,536,537,540,541,544,545,548,549,552,553,556,557,560,561,564,565,568,569,572,573,574,575,578,579,584,585,586,587,592,593,594,595,600,601,608,609,616,617,624,625,632,633,636,637,640,641,644,645,648,649,652,653,656,657,660,661,664,665,668,669,674,675,678,679,686,687,690,691,694,695,702,703,712,713,716,717,720,721,724,725,732,733,748,749,752,753,756,757,760,761,768,769,772,773,776,777,780,781,788,789,792,793,796,797,800,801,804,805,808,809,816,817,828,829,840,841,844,845,848,849,852,853,856,857,860,861,864,865,868,869,872,873,876,877,886,887,890,891,894,895,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,936,937,940,941,950,951,954,955,958,959,962,963,966,967,970,971,978,979,982,983,986,987,990,991,994,995,1002,1003,1006,1007,1010,1011,1014,1015,1018,1019,1028,1029,1032,1033,1040,1041,1044,1045,1090,1091,1094,1095,1098,1099,1102,1103,1106,1107,1114,1115,1118,1119,1122,1123,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1154,1155,1162,1163,1170,1171,1178,1179,1186,1187,1194,1195,1198,1199,1202,1203,1206,1207,1210,1211,1214,1215,1218,1219,1226,1227,1230,1231,1234,1235,1238,1239,1242,1243,1246,1247,1322,1323,1326,1327,1330,1331,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1370,1371,1374,1375,1378,1379,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,336,337,340,341,344,345,348,349,352,353,356,357,364,365,372,373,376,377,380,381,388,389,396,397,404,405,408,409,412,413,416,417,420,421,424,425,426,427,436,437,440,441,444,445,448,449,452,453,460,461,464,465,468,469,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,516,517,520,521,524,525,528,529,536,537,540,541,544,545,548,549,552,553,556,557,560,561,564,565,568,569,572,573,578,579,584,585,586,587,592,593,594,595,600,601,602,603,608,609,616,617,624,625,632,633,636,637,640,641,644,645,648,649,652,653,656,657,660,661,664,665,668,669,674,675,678,679,686,687,690,691,694,695,702,703,712,713,716,717,720,721,724,725,732,733,748,749,752,753,756,757,760,761,768,769,772,773,776,777,780,781,788,789,792,793,796,797,800,801,804,805,808,809,816,817,840,841,844,845,848,849,852,853,856,857,860,861,864,865,868,869,872,873,876,877,886,887,890,891,894,895,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,936,937,940,941,950,951,954,955,958,959,962,963,966,967,970,971,978,979,982,983,986,987,990,991,994,995,1002,1003,1006,1007,1010,1011,1014,1015,1018,1019,1028,1029,1032,1033,1040,1041,1044,1045,1090,1091,1094,1095,1098,1099,1102,1103,1106,1107,1114,1115,1118,1119,1122,1123,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1154,1155,1162,1163,1170,1171,1178,1179,1186,1187,1194,1195,1198,1199,1202,1203,1206,1207,1210,1211,1214,1215,1218,1219,1226,1227,1230,1231,1234,1235,1238,1239,1242,1243,1246,1247,1322,1323,1326,1327,1330,1331,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1370,1371,1374,1375,1378,1379,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,336,337,340,341,344,345,348,349,352,353,356,357,364,365,372,373,376,377,380,381,388,389,396,397,404,405,408,409,412,413,416,417,420,421,424,425,436,437,440,441,444,445,448,449,452,453,460,461,464,465,468,469,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,516,517,520,521,524,525,528,529,536,537,540,541,544,545,548,549,552,553,556,557,560,561,564,565,568,569,572,573,578,579,584,585,586,587,592,593,600,601,608,609,616,617,624,625,632,633,636,637,640,641,644,645,648,649,652,653,656,657,660,661,664,665,668,669,674,675,678,679,804,805,808,809,816,817,828,829,840,841,844,845,848,849,856,857,860,861,864,865,868,869,872,873,876,877,886,887,890,891,894,895,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,936,937,940,941,950,951,954,955,958,959,962,963,966,967,970,971,978,979,982,983,986,987,990,991,994,995,1002,1003,1006,1007,1010,1011,1014,1015,1018,1019,1028,1029,1032,1033,1040,1041,1044,1045,1090,1091,1094,1095,1098,1099,1102,1103,1106,1107,1114,1115,1118,1119,1122,1123,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1154,1155,1194,1195,1198,1199,1202,1203,1206,1207,1210,1211,1214,1215,1218,1219,1226,1227,1230,1231,1234,1235,1238,1239,1242,1243,1246,1247,1322,1323,1326,1327,1330,1331,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1370,1371,1374,1375,1378,1379,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,334,335,338,339,348,349,352,353,356,357,360,361,364,365,368,369,376,377,384,385,388,389,392,393,400,401,408,409,416,417,420,421,424,425,428,429,432,433,436,437,438,439,448,449,452,453,456,457,460,461,464,465,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,512,513,516,517,520,521,528,529,532,533,536,537,540,541,548,549,552,553,556,557,560,561,564,565,568,569,572,573,576,577,580,581,584,585,586,587,590,591,596,597,598,599,604,605,606,607,612,613,620,621,628,629,636,637,644,645,648,649,652,653,656,657,660,661,664,665,668,669,672,673,676,677,680,681,686,687,690,691,702,703,706,707,724,725,728,729,732,733,736,737,744,745,760,761,764,765,768,769,772,773,780,781,784,785,788,789,792,793,800,801,804,805,808,809,812,813,816,817,820,821,828,829,852,853,856,857,860,861,864,865,868,869,872,873,876,877,880,881,884,885,888,889,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,938,939,942,943,946,947,948,949,952,953,962,963,966,967,970,971,974,975,978,979,982,983,990,991,994,995,998,999,1002,1003,1006,1007,1014,1015,1018,1019,1022,1023,1026,1027,1030,1031,1040,1041,1044,1045,1048,1049,1052,1053,1056,1057,1102,1103,1106,1107,1110,1111,1114,1115,1118,1119,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1150,1151,1154,1155,1158,1159,1166,1167,1174,1175,1182,1183,1190,1191,1198,1199,1206,1207,1210,1211,1214,1215,1218,1219,1222,1223,1226,1227,1230,1231,1238,1239,1242,1243,1246,1247,1250,1251,1254,1255,1258,1259,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1366,1367,1370,1371,1374,1375,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475,1478,1479,1482,1483,1486,1487) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [423]:
x = pd.read_csv('combined/2010 combined.csv')

/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,336,337,340,341,344,345,348,349,352,353,356,357,364,365,372,373,376,377,380,381,388,389,404,405,408,409,412,413,416,417,420,421,424,425,436,437,440,441,444,445,448,449,452,453,460,461,464,465,468,469,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,516,517,520,521,524,525,528,529,536,537,540,541,544,545,548,549,552,553,556,557,560,561,564,565,568,569,572,573,574,575,578,579,584,585,586,587,592,593,594,595,600,601,608,609,616,617,624,625,632,633,636,637,640,641,644,645,648,649,652,653,656,657,660,661,664,665,668,669,674,675,678,679,694,695,804,805,808,809,816,817,840,841,844,845,848,849,860,861,864,865,868,869,872,873,876,877,886,887,890,891,894,895,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,936,937,940,941,950,951,954,955,958,959,962,963,966,967,970,971,978,979,982,983,986,987,990,991,994,995,1002,1003,1006,1007,1010,1011,1014,1015,1018,1019,1028,1029,1032,1033,1040,1041,1044,1045,1114,1115,1118,1119,1122,1123,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1154,1155,1194,1195,1198,1199,1202,1203,1206,1207,1210,1211,1214,1215,1218,1219,1226,1227,1230,1231,1234,1235,1238,1239,1242,1243,1246,1247,1322,1323,1326,1327,1330,1331,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1370,1371,1374,1375,1378,1379,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [403]:
d_2010 =pd.read_csv('combined/2010 combined.csv').columns
d_2011 = pd.read_csv('combined/2011 combined.csv').columns
d_2012 =pd.read_csv('combined/2012 combined.csv').columns
d_2013 = pd.read_csv('combined/2013 combined.csv').columns
d_2014 =pd.read_csv('combined/2014 combined.csv').columns
d_2015 = pd.read_csv('combined/2015 combined.csv').columns
d_2016 =pd.read_csv('combined/2016 combined.csv').columns
d_2017 = pd.read_csv('combined/2017 combined.csv').columns

In [414]:
l = [d_2010,d_2011,d_2012,d_2013,d_2014,d_2015,d_2016,d_2017]
import numpy as np
share_columns = l[0]
for i in range(7):
    share_columns = np.intersect1d(share_columns,l[i+1])
# pd.Series(x) # 278 columns are the same

In [415]:
len(share_columns)

290

In [427]:
path = os.path.join(directory, 'combined')
for d in os.listdir(path):
    if d.endswith("d.csv"):
        df = pd.read_csv(os.path.join(path, d))
        final_df = df[share_columns]
        final_df.to_csv(os.path.join(path, d))

/home/guangya/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,68,69,74,75,78,79,82,83,86,87,94,95,98,99,106,107,110,111,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,158,159,162,163,166,167,170,171,174,175,178,179,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,238,239,242,243,246,247,250,251,254,255,258,259,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,334,335,338,339,348,349,352,353,356,357,360,361,364,365,368,369,376,377,384,385,388,389,392,393,416,417,420,421,424,425,428,429,432,433,436,437,438,439,448,449,452,453,456,457,460,461,464,465,472,473,476,477,480,481,484,485,488,489,492,493,496,497,500,501,504,505,508,509,512,513,516,517,520,521,528,529,532,533,536,537,540,541,548,549,552,553,556,557,560,561,564,565,568,569,572,573,576,577,580,581,584,585,590,591,596,597,598,599,604,605,606,607,612,613,620,621,628,629,636,637,644,645,648,649,652,653,656,657,660,661,664,665,668,669,672,673,676,677,680,681,686,687,690,691,702,703,706,707,724,725,728,729,732,733,736,737,744,745,760,761,764,765,768,769,772,773,800,801,804,805,808,809,812,813,816,817,820,821,828,829,852,853,856,857,860,861,872,873,876,877,880,881,884,885,888,889,898,899,902,903,906,907,910,911,914,915,918,919,922,923,926,927,930,931,934,935,938,939,942,943,946,947,948,949,952,953,962,963,966,967,970,971,974,975,978,979,982,983,990,991,994,995,998,999,1002,1003,1006,1007,1014,1015,1018,1019,1022,1023,1026,1027,1030,1031,1040,1041,1044,1045,1052,1053,1056,1057,1102,1103,1106,1107,1110,1111,1114,1115,1118,1119,1126,1127,1130,1131,1134,1135,1138,1139,1142,1143,1146,1147,1150,1151,1154,1155,1158,1159,1166,1167,1174,1175,1182,1183,1190,1191,1198,1199,1206,1207,1210,1211,1214,1215,1218,1219,1222,1223,1226,1227,1230,1231,1238,1239,1242,1243,1246,1247,1250,1251,1254,1255,1258,1259,1334,1335,1338,1339,1342,1343,1346,1347,1350,1351,1354,1355,1358,1359,1362,1363,1366,1367,1370,1371,1374,1375,1382,1383,1386,1387,1390,1391,1394,1395,1398,1399,1402,1403,1406,1407,1410,1411,1414,1415,1418,1419,1422,1423,1426,1427,1430,1431,1434,1435,1438,1439,1442,1443,1446,1447,1450,1451,1454,1455,1458,1459,1462,1463,1466,1467,1470,1471,1474,1475,1478,1479,1482,1483,1486,1487) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [428]:
x = pd.read_csv('combined/2010 combined.csv')
x

,Unnamed: 0,Estimate; ANCESTRY - Total population,Estimate; CLASS OF WORKER - Civilian employed population 16 years and over,Estimate; COMMUTING TO WORK - Mean travel time to work (minutes),Estimate; COMMUTING TO WORK - Workers 16 years and over,Estimate; DISABILITY STATUS OF THE CIVILIAN NONINSTITUTIONALIZED POPULATION - 18 to 64 years,Estimate; DISABILITY STATUS OF THE CIVILIAN NONINSTITUTIONALIZED POPULATION - 65 years and over,Estimate; DISABILITY STATUS OF THE CIVILIAN NONINSTITUTIONALIZED POPULATION - Total Civilian Noninstitutionalized Population,Estimate; DISABILITY STATUS OF THE CIVILIAN NONINSTITUTIONALIZED POPULATION - Under 18 years,Estimate; EDUCATIONAL ATTAINMENT - Percent bachelor's degree or higher,...,Percent; SEX AND AGE - Median age (years),Percent; SEX AND AGE - Total population,Percent; SEX AND AGE - Under 5 years,Percent; U.S. CITIZENSHIP STATUS - Foreign-born population,Percent; VETERAN STATUS - Civilian population 18 years and over,"Percent; WORLD REGION OF BIRTH OF FOREIGN BORN - Foreign-born population, excluding population born at sea",Percent; YEAR OF ENTRY - Foreign born,Percent; YEAR OF ENTRY - Native,Percent; YEAR OF ENTRY - Population born outside the United States,Unnamed: 0.1
0,0,5095,2350,31.7,2340,3079,1011,5095,1005,(X),...,(X),5095,6.2,1401,4090,1401,1401,39,1440,147
1,1,6548,3712,32.0,3640,4186,1079,6366,1101,(X),...,(X),6548,4.5,932,5447,932,932,35,967,148
2,2,5943,2449,28.4,2420,3274,1400,5666,992,(X),...,(X),5943,4.7,1093,4951,1093,1093,56,1149,149
3,3,3061,1541,31.7,1532,1851,427,3061,783,(X),...,(X),3061,8.2,300,2278,300,300,42,342,150
4,4,5611,2960,29.9,2944,3368,1046,5611,1197,(X),...,(X),5611,7.0,1215,4414,1215,1215,169,1384,151
5,5,5030,2648,35.1,2640,3206,751,5030,1073,(X),...,(X),5030,6.0,1275,3957,1275,1275,38,1313,152
6,6,4714,2271,31.4,2213,2845,945,4714,924,(X),...,(X),4714,6.2,1169,3790,1169,1169,41,1210,153
7,7,4388,2487,35.2,2476,3338,142,4288,808,(X),...,(X),4388,5.7,756,3580,756,756,13,769,1
8,8,7032,3117,35.1,3028,4972,432,7019,1615,(X),...,(X),7032,8.0,1990,5410,1990,1990,58,2048,2
9,9,2275,1130,31.0,1110,1424,211,1966,331,(X),...,(X),2275,7.7,759,1906,759,759,67,826,3
10,10,6205,3081,42.2,3035,3954,432,5249,863,(X),...,(X),6205,5.9,1563,5333,1563,1563,55,1618,4
11,11,3906,2180,36.9,2180,3065,376,3898,457,(X),...,(X),3906,7.3,905,3442,905,905,31,936,6
12,12,3045,1870,35.0,1846,2663,112,3045,270,(X),...,(X),3045,1.6,693,2775,693,693,52,745,7
13,13,2112,998,36.9,983,1290,636,2090,164,(X),...,(X),2112,4.2,642,1926,642,642,15,657,8
14,14,6624,3908,41.0,3890,5038,370,6436,1028,(X),...,(X),6624,4.9,1532,5585,1532,1532,121,1653,9
15,15,3921,2014,34.6,1975,2567,352,3921,1002,(X),...,(X),3921,10.3,1332,2919,1332,1332,89,1421,10
16,16,5608,2948,38.0,2940,3883,138,5597,1576,(X),...,(X),5608,5.7,2394,4025,2394,2394,28,2422,11
17,17,5248,2565,30.3,2529,3225,924,5248,1099,(X),...,(X),5248,8.6,1000,4149,1000,1000,144,1144,154
18,18,3057,1527,28.9,1514,1920,551,3057,586,(X),...,(X),3057,5.4,925,2471,925,925,92,1017,155
19,19,5241,2899,30.2,2836,3484,812,5241,945,(X),...,(X),5241,4.4,1689,4296,1689,1689,144,1833,156
20,20,4442,2426,36.2,2379,3030,739,4442,673,(X),...,(X),4442,5.1,1638,3769,1638,1638,88,1726,157
21,21,5232,2817,38.5,2735,3444,610,5223,1169,(X),...,(X),5232,5.1,1413,4056,1413,1413,110,1523,158
22,22,3535,1724,43.6,1658,2242,464,3535,829,(X),...,(X),3535,12.2,1090,2706,1090,1090,11,1101,159
23,23,3820,1857,31.9,1821,2159,584,3820,1077,(X),...,(X),3820,6.1,197,2743,197,197,44,241,160
24,24,4613,2253,32.2,2221,2468,955,4613,1190,(X),...,(X),4613,6.4,795,3423,795,795,9,804,161
25,25,6600,3395,31.4,3297,3944,1051,6600,1605,(X),...,(X),6600,7.7,1424,4995,1424,1424,51,1475,162
26,26,3598,1749,34.2,1714,2240,424,3598,934,(X),...,(X),3598,5.7,810,2664,810,810,81,891,163
27,27,5510,1907,30.1,1852,2251,1799,5322,1272,(X),...,(X),5510,5.8,1894,4238,1894,1894,260,2154,164
28,28,1664,894,30.5,889,1064,234,1664,366,(X),...,(X),1664,7.2,501,1298,501,501,20,521,165
29,29,5496,2479,34.2,2385,3562,790,5496,1144,(X),...,(X),5496,6.7,2501,4352,2501,2501,96,2597,166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,1470,4041,2065,34.2,1984,2548,193,4041,1300,(X),...,(X),4041,7.4,1122,2741,1122,1122,38,1160,1511
1471,1471,4673,2409,33.1,2337,2901,380,4673,1392,(X),...,(X),4673,7.3,703,3281,703,703,31,734,1512
1472,1472,5138,2965,32.7,2900,3611,305,5138,1222,(X),...,(X),5138,11.1,1903,3916,1903,1903,63,1966,1513
1473,1473,4015,2306,33.9,2262,2860,229,3953,864,(X),...,(X),4015,11.4,1009,3102,1009,1009,0,1009,1514
1474,1474,4721,2626,34.0,2574,2989,396,4249,864,(X),...,(X),4721,6.6,914,3857,914,914,9,923,1515
1475,1475,3790,1825,31.0,1778,2117,787,3612,708,(X),...,(X),3790,6.0,544,3082,544,544,39,583,1516
1476,1476,6561,3149,24.0,3133,4176,813,6367,1378,(X),...,(X),6561,6.3,1351,5167,1351,1351,10,1361,1517
1477,1477,2500,1427,36.8,1421,1709,127,2500,664,(X),...,(X),2500,9.7,510,1836,510,510,79,589,1518
1478,1478,5192,2834,38.5,2660,3429,264,5176,1483,(X),...,(X),5192,11.6,1207,3693,1207,1207,17,1224,1519
1479,1479,2838,1683,32.6,1655,2007,198,2838,633,(X),...,(X),2838,3.7,601,2205,601,601,12,613,1520
1480,1480,6827,3571,32.1,3413,4359,376,6827,2092,(X),...,(X),6827,9.5,1070,4735,1070,1070,29,1099,1521
1481,1481,2778,1358,41.7,1310,1704,249,2778,825,(X),...,(X),2778,6.0,769,1953,769,769,31,800,1522
1482,1482,4254,2049,37.2,2029,2675,176,4254,1403,(X),...,(X),4254,6.0,1113,2851,1113,1113,30,1143,1523
1483,1483,5439,3067,30.9,3008,3795,209,5439,1435,(X),...,(X),5439,6.2,1350,4004,1350,1350,21,1371,1524
1484,1484,6228,3824,32.0,3683,4095,447,6228,1686,(X),...,(X),6228,6.2,1145,4542,1145,1145,186,1331,1525
1485,1485,3638,2216,33.5,2159,2536,168,3638,934,(X),...,(X),3638,4.6,438,2704,438,438,54,492,1526
1486,1486,2952,1574,34.1,1559,1884,262,2952,806,(X),...,(X),2952,8.3,695,2146,695,695,17,712,1527
1487,1487,5213,2661,33.3,2629,3302,576,5213,1335,(X),...,(X),5213,4.9,449,3878,449,449,172,621,1528
1488,1488,3801,2069,36.8,2058,2695,82,3774,997,(X),...,(X),3801,8.1,1273,2777,1273,1273,68,1341,1529
1489,1489,2720,1354,33.6,1328,1620,418,2720,682,(X),...,(X),2720,7.7,127,2038,127,127,50,177,1530
1490,1490,4881,2499,35.8,2420,3137,452,4881,1292,(X),...,(X),4881,5.7,1221,3589,1221,1221,46,1267,1531
1491,1491,4264,1854,30.9,1804,2518,265,4254,1471,(X),...,(X),4264,11.6,1841,2783,1841,1841,99,1940,1532
1492,1492,3590,1949,21.7,1887,2261,534,3590,795,(X),...,(X),3590,4.5,1404,2795,1404,1404,82,1486,1533
1493,1493,4695,2377,23.1,2293,3069,371,4695,1255,(X),...,(X),4695,8.2,1653,3440,1653,1653,34,1687,1534
1494,1494,4576,2331,24.0,2275,3054,534,4576,988,(X),...,(X),4576,7.6,1177,3588,1177,1177,84,1261,1535
1495,1495,3293,1730,27.3,1720,1985,638,3293,670,(X),...,(X),3293,4.5,374,2623,374,374,22,396,144
1496,1496,6556,3807,33.6,3729,4231,947,6556,1378,(X),...,(X),6556,3.3,771,5178,771,771,68,839,145
1497,1497,1301,650,31.2,629,809,206,1301,286,(X),...,(X),1301,10.9,138,1015,138,138,0,138,146
1498,1498,0,0,-,0,0,0,0,0,(X),...,(X),0,-,0,0,0,0,0,0,1317
1499,1499,0,0,-,0,0,0,0,0,(X),...,(X),0,-,0,0,0,0,0,0,1318